import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import styled from 'styled-components'

const Title = styled.h1`
color: red;
`


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet" />
      </Head>

      <Title>
        Title red
      </Title>
      <Link href="/blog">
        Blog
      </Link>

      <Navbar />
    </div>
  )
}
